package com.easy1auth.adminaccess;
import com.easy1auth.adminaccess.model.*; import com.easy1auth.adminidentity.model.*; import com.easy1auth.foundation.error.DomainException; import com.easy1auth.foundation.id.UuidV7; import com.easy1auth.tenant.TenantContext; import com.easy1auth.tenant.model.*; import org.babyfish.jimmer.sql.JSqlClient; import org.babyfish.jimmer.sql.ast.LikeMode; import org.babyfish.jimmer.sql.ast.mutation.SaveMode; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.Instant; import java.util.*;
@Service public class AdminAccessService{
 public static final List<String> PERMISSIONS=List.of("admin-user:read","admin-user:update","admin-user:status","admin-user:reset-password","admin-user:reset-mfa","admin-user:assign-role","admin-user:remove-tenant","admin-role:read","admin-role:create","admin-role:update","admin-role:delete","admin-role:assign");
 private static final AdminRoleEntityTable ROLE=AdminRoleEntityTable.$; private static final TenantMembershipEntityTable MEMBERSHIP=TenantMembershipEntityTable.$; private static final AdminAccountEntityTable ACCOUNT=AdminAccountEntityTable.$;
 private final JSqlClient sql; public AdminAccessService(JSqlClient sql){this.sql=sql;}
 @Transactional(readOnly=true) public Page<AdminRoleView> roles(TenantContext c,int page,int pageSize,String name,Boolean system){require(c,"admin-role:read");int p=Math.max(1,page),size=Math.min(100,Math.max(1,pageSize));var query=sql.createQuery(ROLE).where(ROLE.tenantId().eq(c.tenantId())).whereIf(name!=null,()->ROLE.name().ilike(name,LikeMode.ANYWHERE)).whereIf(system!=null,()->ROLE.systemRole().eq(system)).orderBy(ROLE.createdAt().desc()).select(ROLE.fetch(AdminRoleEntityFetcher.$.allScalarFields().memberships()));long total=query.fetchUnlimitedCount();return new Page<>(query.limit(size,(long)(p-1)*size).execute().stream().map(this::view).toList(),total,p,size);}
 @Transactional(readOnly=true) public AdminRoleView role(TenantContext c,UUID id){require(c,"admin-role:read");return find(c.tenantId(),id);}
 @Transactional public AdminRoleView create(TenantContext c,String name,String description,List<String> permissions){require(c,"admin-role:create");validate(name,permissions);requireGrantable(c,permissions);UUID id=UuidV7.randomUuid();Instant now=Instant.now();sql.saveCommand(AdminRoleEntityDraft.$.produce(d->d.setId(id).setTenantId(c.tenantId()).setName(name.strip()).setDescription(description).setPermissions(permissions).setSystemRole(false).setCreatedAt(now).setUpdatedAt(now))).setMode(SaveMode.INSERT_ONLY).execute();return find(c.tenantId(),id);}
 @Transactional public AdminRoleView update(TenantContext c,UUID id,String name,String description,List<String> permissions){require(c,"admin-role:update");var old=findEntity(c.tenantId(),id);if(old.systemRole())throw immutable();var n=name==null?old.name():name;var p=permissions==null?old.permissions():permissions;validate(n,p);requireGrantable(c,p);var update=sql.createUpdate(ROLE).set(ROLE.name(),n.strip()).set(ROLE.permissions(),p).set(ROLE.updatedAt(),Instant.now()).where(ROLE.id().eq(id),ROLE.tenantId().eq(c.tenantId()));if(description!=null)update.set(ROLE.description(),description);update.execute();return find(c.tenantId(),id);}
 @Transactional public void delete(TenantContext c,UUID id){require(c,"admin-role:delete");if(findEntity(c.tenantId(),id).systemRole())throw immutable();sql.deleteById(AdminRoleEntity.class,id);}
 @Transactional(readOnly=true) public MemberPage members(TenantContext c,int page,int pageSize,String username,String email,String status,UUID roleId){require(c,"admin-user:read");int p=Math.max(1,page),size=Math.min(100,Math.max(1,pageSize));var memberships=sql.createQuery(MEMBERSHIP).where(MEMBERSHIP.tenantId().eq(c.tenantId()),MEMBERSHIP.status().eq("active")).select(MEMBERSHIP).execute();if(roleId!=null){var allowed=membersForRole(c.tenantId(),roleId);memberships=memberships.stream().filter(m->allowed.contains(m.id())).toList();}var byAccount=new HashMap<UUID,TenantMembershipEntity>();memberships.forEach(m->byAccount.put(m.accountId(),m));if(byAccount.isEmpty())return new MemberPage(List.of(),0,p,size);var query=sql.createQuery(ACCOUNT).where(ACCOUNT.id().in(byAccount.keySet())).whereIf(username!=null,()->ACCOUNT.username().ilike(username,LikeMode.ANYWHERE)).whereIf(email!=null,()->ACCOUNT.email().ilike(email,LikeMode.ANYWHERE)).whereIf(status!=null,()->ACCOUNT.status().eq(status)).orderBy(ACCOUNT.createdAt().desc()).select(ACCOUNT);long total=query.fetchUnlimitedCount();var rows=query.limit(size,(long)(p-1)*size).execute().stream().map(a->memberView(a,byAccount.get(a.id()),c.tenantId())).toList();return new MemberPage(rows,total,p,size);}
 @Transactional(readOnly=true) public AdminMemberView member(TenantContext c,UUID account){require(c,"admin-user:read");var m=findMembership(c.tenantId(),account);var a=sql.findById(AdminAccountEntity.class,account);if(a==null)throw memberMissing();return memberView(a,m,c.tenantId());}
 @Transactional public void assignRoles(TenantContext c,UUID account,List<UUID> roleIds){require(c,"admin-user:assign-role");var m=findMembership(c.tenantId(),account);if("owner".equals(m.membershipRole()))throw new DomainException("OWNER_ROLE_IMMUTABLE","owner 不使用自定义角色分配",409);var current=rolesForMembership(m.id());var associations=sql.getAssociations(AdminRoleEntityProps.MEMBERSHIPS);current.forEach(r->associations.delete(r.id(),m.id()));for(UUID roleId:roleIds){findEntity(c.tenantId(),roleId);associations.insert(roleId,m.id());}}
 @Transactional public void removeMember(TenantContext c,UUID account){require(c,"admin-user:remove-tenant");if(c.accountId().equals(account))throw new DomainException("SELF_REMOVE_DENIED","不能将自己移出租户",409);var m=findMembership(c.tenantId(),account);if("owner".equals(m.membershipRole()))throw new DomainException("OWNER_CANNOT_REMOVE","owner 必须先转移所有权",409);sql.deleteById(TenantMembershipEntity.class,m.id());}
 @Transactional public void ensureDefaultRoles(UUID tenant){ensureSystemRole(tenant,"超级管理员","拥有所有权限的系统管理员",List.of("*"));ensureSystemRole(tenant,"只读管理员","仅拥有查看权限的系统管理员",PERMISSIONS.stream().filter(p->p.endsWith(":read")).toList());}
 @Transactional(readOnly=true) public Map<String,Long> roleStats(TenantContext c){require(c,"admin-role:read");var roles=sql.createQuery(ROLE).where(ROLE.tenantId().eq(c.tenantId())).select(ROLE.fetch(AdminRoleEntityFetcher.$.allScalarFields().memberships())).execute();return Map.of("totalRoles",(long)roles.size(),"systemRoles",roles.stream().filter(AdminRoleEntity::systemRole).count(),"customRoles",roles.stream().filter(r->!r.systemRole()).count(),"totalAdmins",roles.stream().flatMap(r->r.memberships().stream()).map(TenantMembershipEntity::id).distinct().count());}
 @Transactional(readOnly=true) public Map<String,Long> memberStats(TenantContext c){require(c,"admin-user:read");var ms=sql.createQuery(MEMBERSHIP).where(MEMBERSHIP.tenantId().eq(c.tenantId()),MEMBERSHIP.status().eq("active")).select(MEMBERSHIP).execute();var accounts=ms.isEmpty()?List.<AdminAccountEntity>of():sql.findByIds(AdminAccountEntity.class,ms.stream().map(TenantMembershipEntity::accountId).toList());return Map.of("totalAdmins",(long)accounts.size(),"activeAdmins",accounts.stream().filter(a->"active".equals(a.status())).count(),"disabledAdmins",accounts.stream().filter(a->"disabled".equals(a.status())).count(),"mfaEnabledAdmins",accounts.stream().filter(AdminAccountEntity::mfaEnabled).count(),"ownerCount",ms.stream().filter(m->"owner".equals(m.membershipRole())).count());}
 public void require(TenantContext c,String permission){if(!c.hasPermission(permission))throw new DomainException("PERMISSION_DENIED","权限不足",403);}
 private AdminRoleView find(UUID tenant,UUID id){return view(findEntityFetched(tenant,id));} private AdminRoleEntity findEntity(UUID tenant,UUID id){return sql.createQuery(ROLE).where(ROLE.id().eq(id),ROLE.tenantId().eq(tenant)).select(ROLE).fetchOptional().orElseThrow(()->new DomainException("ADMIN_ROLE_NOT_FOUND","管理员角色不存在",404));} private AdminRoleEntity findEntityFetched(UUID tenant,UUID id){return sql.createQuery(ROLE).where(ROLE.id().eq(id),ROLE.tenantId().eq(tenant)).select(ROLE.fetch(AdminRoleEntityFetcher.$.allScalarFields().memberships())).fetchOptional().orElseThrow(()->new DomainException("ADMIN_ROLE_NOT_FOUND","管理员角色不存在",404));}
 private Set<UUID> membersForRole(UUID tenant,UUID role){return findEntityFetched(tenant,role).memberships().stream().map(TenantMembershipEntity::id).collect(java.util.stream.Collectors.toSet());} private List<AdminRoleEntity> rolesForMembership(UUID membership){return sql.createQuery(ROLE).where(ROLE.memberships(m->m.id().eq(membership))).select(ROLE).execute();}
 private TenantMembershipEntity findMembership(UUID tenant,UUID account){return sql.createQuery(MEMBERSHIP).where(MEMBERSHIP.tenantId().eq(tenant),MEMBERSHIP.accountId().eq(account),MEMBERSHIP.status().eq("active")).select(MEMBERSHIP).fetchOptional().orElseThrow(this::memberMissing);}
 private AdminMemberView memberView(AdminAccountEntity a,TenantMembershipEntity m,UUID tenant){return new AdminMemberView(a.id(),tenant,m.membershipRole(),a.lastTenantId(),a.username(),a.email(),a.phone(),a.status(),a.mfaEnabled(),a.mfaType(),a.lastLoginAt(),a.createdAt(),a.updatedAt(),rolesForMembership(m.id()).stream().map(this::viewWithoutMemberships).toList());}
 private AdminRoleView view(AdminRoleEntity r){return new AdminRoleView(r.id(),r.tenantId(),r.name(),r.description(),r.permissions(),r.systemRole(),r.memberships().size(),r.createdAt(),r.updatedAt());} private AdminRoleView viewWithoutMemberships(AdminRoleEntity r){return new AdminRoleView(r.id(),r.tenantId(),r.name(),r.description(),r.permissions(),r.systemRole(),0,r.createdAt(),r.updatedAt());}
 private void ensureSystemRole(UUID tenant,String name,String description,List<String> permissions){boolean exists=sql.createQuery(ROLE).where(ROLE.tenantId().eq(tenant),ROLE.name().eq(name)).select(ROLE.id()).exists();if(!exists){Instant now=Instant.now();sql.saveCommand(AdminRoleEntityDraft.$.produce(d->d.setId(UuidV7.randomUuid()).setTenantId(tenant).setName(name).setDescription(description).setPermissions(permissions).setSystemRole(true).setCreatedAt(now).setUpdatedAt(now))).setMode(SaveMode.INSERT_ONLY).execute();}}
 private void validate(String name,List<String> permissions){if(name==null||name.isBlank()||name.length()>100)throw new DomainException("ROLE_NAME_INVALID","角色名称无效",400);if(permissions==null||permissions.stream().anyMatch(p->!PERMISSIONS.contains(p)&&!"*".equals(p)))throw new DomainException("PERMISSION_INVALID","包含未知权限",400);} private void requireGrantable(TenantContext c,List<String> p){if(!c.permissions().contains("*")&&p.stream().anyMatch(x->!c.permissions().contains(x)))throw new DomainException("PERMISSION_ESCALATION","不能授予自己不具备的权限",403);} private DomainException memberMissing(){return new DomainException("ADMIN_MEMBER_NOT_FOUND","管理员不属于当前租户",404);} private DomainException immutable(){return new DomainException("SYSTEM_ROLE_IMMUTABLE","系统角色不能修改或删除",409);}
 public record Page<T>(List<T> roles,long total,int page,int pageSize){} public record MemberPage(List<AdminMemberView> admins,long total,int page,int pageSize){}
}
