package com.easy1auth.adminaccess;

import java.util.Arrays;
import java.util.Optional;

public enum ManagementPermissionCode {
    MENU_DASHBOARD("menu:dashboard", ManagementPermissionScope.TENANT, ManagementPermissionType.MENU),
    DIRECTORY_USER_MANAGEMENT("menu:user-management", ManagementPermissionScope.TENANT, ManagementPermissionType.DIRECTORY),
    MENU_USER("menu:user", ManagementPermissionScope.TENANT, ManagementPermissionType.MENU),
    MENU_GROUP("menu:group", ManagementPermissionScope.TENANT, ManagementPermissionType.MENU),
    MENU_POSITION("menu:position", ManagementPermissionScope.TENANT, ManagementPermissionType.MENU),
    MENU_ROLE("menu:role", ManagementPermissionScope.TENANT, ManagementPermissionType.MENU),
    MENU_PERMISSION("menu:permission", ManagementPermissionScope.TENANT, ManagementPermissionType.MENU),
    MENU_ADMIN_USER("menu:admin-user", ManagementPermissionScope.PLATFORM, ManagementPermissionType.MENU),
    MENU_APPLICATION("menu:application", ManagementPermissionScope.TENANT, ManagementPermissionType.MENU),
    MENU_SOCIAL_IDENTITY_PROVIDER("menu:social-identity-provider", ManagementPermissionScope.TENANT, ManagementPermissionType.MENU),
    DIRECTORY_PLATFORM_MANAGEMENT("directory:platform-management", ManagementPermissionScope.PLATFORM, ManagementPermissionType.DIRECTORY),
    MENU_TENANT("menu:tenant", ManagementPermissionScope.PLATFORM, ManagementPermissionType.MENU),
    MENU_TENANT_PACKAGE("menu:tenant-package", ManagementPermissionScope.PLATFORM, ManagementPermissionType.MENU),
    MENU_MENU_MANAGEMENT("menu:menu-management", ManagementPermissionScope.PLATFORM, ManagementPermissionType.MENU),
    MENU_BRAND_SETTINGS("menu:brand-settings", ManagementPermissionScope.TENANT, ManagementPermissionType.MENU),
    MENU_SECURITY("menu:security", ManagementPermissionScope.TENANT, ManagementPermissionType.MENU),
    MENU_PERSONALIZATION("menu:personalization", ManagementPermissionScope.TENANT, ManagementPermissionType.MENU),
    MENU_AUDIT("menu:audit", ManagementPermissionScope.TENANT, ManagementPermissionType.MENU),
    ADMIN_USER_LIST("admin-user:list", ManagementPermissionScope.PLATFORM, ManagementPermissionType.ACTION),
    ADMIN_USER_STATS("admin-user:stats", ManagementPermissionScope.PLATFORM, ManagementPermissionType.ACTION),
    ADMIN_USER_READ("admin-user:read", ManagementPermissionScope.PLATFORM, ManagementPermissionType.ACTION),
    ADMIN_USER_CREATE("admin-user:create", ManagementPermissionScope.PLATFORM, ManagementPermissionType.ACTION),
    ADMIN_USER_UPDATE("admin-user:update", ManagementPermissionScope.PLATFORM, ManagementPermissionType.ACTION),
    ADMIN_USER_STATUS("admin-user:status", ManagementPermissionScope.PLATFORM, ManagementPermissionType.ACTION),
    ADMIN_USER_RESET_PASSWORD("admin-user:reset-password", ManagementPermissionScope.PLATFORM, ManagementPermissionType.ACTION),
    ADMIN_USER_RESET_MFA("admin-user:reset-mfa", ManagementPermissionScope.PLATFORM, ManagementPermissionType.ACTION),
    ADMIN_USER_ASSIGN_ROLE("admin-user:assign-role", ManagementPermissionScope.PLATFORM, ManagementPermissionType.ACTION),
    ADMIN_USER_REMOVE_TENANT("admin-user:remove-tenant", ManagementPermissionScope.PLATFORM, ManagementPermissionType.ACTION),
    TENANT_LIST("tenant:list", ManagementPermissionScope.PLATFORM, ManagementPermissionType.ACTION),
    TENANT_CREATE("tenant:create", ManagementPermissionScope.PLATFORM, ManagementPermissionType.ACTION),
    TENANT_READ("tenant:read", ManagementPermissionScope.PLATFORM, ManagementPermissionType.ACTION),
    TENANT_UPDATE("tenant:update", ManagementPermissionScope.PLATFORM, ManagementPermissionType.ACTION),
    TENANT_STATUS("tenant:status", ManagementPermissionScope.PLATFORM, ManagementPermissionType.ACTION),
    TENANT_DELETE("tenant:delete", ManagementPermissionScope.PLATFORM, ManagementPermissionType.ACTION),
    TENANT_OWNER_TRANSFER("tenant:owner-transfer", ManagementPermissionScope.PLATFORM, ManagementPermissionType.ACTION),
    TENANT_MEMBER_REMOVE("tenant:member-remove", ManagementPermissionScope.PLATFORM, ManagementPermissionType.ACTION),
    MENU_MANAGEMENT_LIST("menu-management:list", ManagementPermissionScope.PLATFORM, ManagementPermissionType.ACTION),
    TENANT_PACKAGE_PERMISSION_CATALOG("tenant-package:permissions-catalog", ManagementPermissionScope.PLATFORM, ManagementPermissionType.ACTION),
    TENANT_PACKAGE_LIST("tenant-package:list", ManagementPermissionScope.PLATFORM, ManagementPermissionType.ACTION),
    TENANT_PACKAGE_READ("tenant-package:read", ManagementPermissionScope.PLATFORM, ManagementPermissionType.ACTION),
    TENANT_PACKAGE_CREATE("tenant-package:create", ManagementPermissionScope.PLATFORM, ManagementPermissionType.ACTION),
    TENANT_PACKAGE_UPDATE("tenant-package:update", ManagementPermissionScope.PLATFORM, ManagementPermissionType.ACTION),
    TENANT_PACKAGE_STATUS("tenant-package:status", ManagementPermissionScope.PLATFORM, ManagementPermissionType.ACTION),
    TENANT_PACKAGE_PERMISSION_REPLACE("tenant-package:permissions-replace", ManagementPermissionScope.PLATFORM, ManagementPermissionType.ACTION),
    TENANT_PACKAGE_DELETE("tenant-package:delete", ManagementPermissionScope.PLATFORM, ManagementPermissionType.ACTION),
    SECURITY_PASSWORD_POLICY_READ("security:password-policy:read", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    SECURITY_PASSWORD_CHANGE("security:password:change", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    SECURITY_MFA_READ("security:mfa:read", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    SECURITY_MFA_SETUP("security:mfa:setup", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    SECURITY_MFA_ENABLE("security:mfa:enable", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    SECURITY_MFA_DISABLE("security:mfa:disable", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    SECURITY_MFA_VERIFY("security:mfa:verify", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    SECURITY_MFA_EMAIL_CODE("security:mfa:email-code", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    APPLICATION_LIST("application:list", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    APPLICATION_STATS("application:stats", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    APPLICATION_READ("application:read", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    APPLICATION_CREATE("application:create", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    APPLICATION_UPDATE("application:update", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    APPLICATION_DELETE("application:delete", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    APPLICATION_STATUS("application:status", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    APPLICATION_REGENERATE_SECRET("application:regenerate-secret", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    SOCIAL_IDENTITY_PROVIDER_LIST("social-identity-provider:list", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    SOCIAL_IDENTITY_PROVIDER_STATS("social-identity-provider:stats", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    SOCIAL_IDENTITY_PROVIDER_READ("social-identity-provider:read", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    SOCIAL_IDENTITY_PROVIDER_CREATE("social-identity-provider:create", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    SOCIAL_IDENTITY_PROVIDER_UPDATE("social-identity-provider:update", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    SOCIAL_IDENTITY_PROVIDER_DELETE("social-identity-provider:delete", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    AUDIT_LIST("audit:list", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    AUDIT_STATS("audit:stats", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    AUDIT_READ("audit:read", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    AUDIT_CLEANUP("audit:cleanup", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    ADMIN_ROLE_STATS("admin-role:stats", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    ADMIN_ROLE_PERMISSIONS_CATALOG("admin-role:permissions-catalog", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    ADMIN_ROLE_LIST("admin-role:list", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    ADMIN_ROLE_READ("admin-role:read", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    ADMIN_ROLE_CREATE("admin-role:create", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    ADMIN_ROLE_UPDATE("admin-role:update", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    ADMIN_ROLE_DELETE("admin-role:delete", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    ADMIN_ROLE_ASSIGN("admin-role:assign", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    USER_LIST("user:list", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    USER_STATS("user:stats", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    USER_READ("user:read", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    USER_CREATE("user:create", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    USER_UPDATE("user:update", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    USER_DELETE("user:delete", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    USER_STATUS("user:status", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    USER_RESET_PASSWORD("user:reset-password", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    USER_CHANGE_PASSWORD("user:change-password", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    USER_ROLES_READ("user:roles:read", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    USER_ROLES_ASSIGN("user:roles:assign", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    USER_GROUPS_READ("user:groups:read", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    USER_GROUPS_ASSIGN("user:groups:assign", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    USER_IMPORT_TEMPLATE("user:import:template", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    USER_IMPORT("user:import", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    USER_ROLE_LIST("user-role:list", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    USER_ROLE_STATS("user-role:stats", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    USER_ROLE_TREE("user-role:tree", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    USER_ROLE_READ("user-role:read", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    USER_ROLE_CREATE("user-role:create", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    USER_ROLE_UPDATE("user-role:update", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    USER_ROLE_DELETE("user-role:delete", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    USER_ROLE_USERS_READ("user-role:users:read", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    USER_ROLE_USERS_ASSIGN("user-role:users:assign", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    USER_ROLE_USERS_REMOVE("user-role:users:remove", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    USER_ROLE_USER_ROLES_READ("user-role:user-roles:read", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    USER_ROLE_USER_ROLES_REPLACE("user-role:user-roles:replace", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    DATA_PERMISSION_LIST("data-permission:list", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    DATA_PERMISSION_STATS("data-permission:stats", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    DATA_PERMISSION_TREE("data-permission:tree", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    DATA_PERMISSION_READ("data-permission:read", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    DATA_PERMISSION_CREATE("data-permission:create", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    DATA_PERMISSION_UPDATE("data-permission:update", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    DATA_PERMISSION_DELETE("data-permission:delete", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    GROUP_LIST("group:list", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    GROUP_TREE("group:tree", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    GROUP_STATS("group:stats", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    GROUP_READ("group:read", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    GROUP_CREATE("group:create", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    GROUP_UPDATE("group:update", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    GROUP_DELETE("group:delete", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    GROUP_MEMBERS_READ("group:members:read", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    GROUP_MEMBERS_ADD("group:members:add", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    GROUP_MEMBERS_REMOVE("group:members:remove", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    GROUP_ADMIN_ADD("group:admin:add", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    GROUP_ADMIN_REMOVE("group:admin:remove", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    POSITION_LIST("position:list", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    POSITION_STATS("position:stats", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    POSITION_READ("position:read", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    POSITION_CREATE("position:create", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    POSITION_UPDATE("position:update", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    POSITION_DELETE("position:delete", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    WEBHOOK_LIST("webhook:list", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    WEBHOOK_CREATE("webhook:create", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    WEBHOOK_UPDATE("webhook:update", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    WEBHOOK_ROTATE_SECRET("webhook:rotate-secret", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    WEBHOOK_DELETE("webhook:delete", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    SECURITY_POLICY_READ("security-policy:read", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    SECURITY_POLICY_UPDATE("security-policy:update", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    BRAND_READ("brand:read", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    BRAND_UPDATE("brand:update", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    LOGIN_STYLE_READ("login-style:read", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    LOGIN_STYLE_UPDATE("login-style:update", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    CUSTOM_DOMAIN_LIST("custom-domain:list", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    CUSTOM_DOMAIN_CREATE("custom-domain:create", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    CUSTOM_DOMAIN_VERIFY("custom-domain:verify", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    CUSTOM_DOMAIN_SSL("custom-domain:ssl", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    CUSTOM_DOMAIN_DELETE("custom-domain:delete", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    MESSAGE_TEMPLATE_LIST("message-template:list", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    MESSAGE_TEMPLATE_CREATE("message-template:create", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    MESSAGE_TEMPLATE_UPDATE("message-template:update", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    MESSAGE_TEMPLATE_DELETE("message-template:delete", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    MESSAGE_TEMPLATE_INIT("message-template:init", ManagementPermissionScope.TENANT, ManagementPermissionType.ACTION),
    DATA_PLATFORM_ALL("data:platform:all", ManagementPermissionScope.PLATFORM, ManagementPermissionType.DATA),
    DATA_TENANT_ALL("data:tenant:all", ManagementPermissionScope.TENANT, ManagementPermissionType.DATA);

    private final String value;
    private final ManagementPermissionScope scope;
    private final ManagementPermissionType type;

    ManagementPermissionCode(String value, ManagementPermissionScope scope, ManagementPermissionType type) {
        this.value = value;
        this.scope = scope;
        this.type = type;
    }

    public String value() {
        return value;
    }

    public ManagementPermissionScope scope() {
        return scope;
    }

    public ManagementPermissionType type() {
        return type;
    }

    public static Optional<ManagementPermissionCode> fromValue(String value) {
        return Arrays.stream(values()).filter(code -> code.value.equals(value)).findFirst();
    }
}
