create table management_permission
(
    code        varchar(150) primary key,
    type        varchar(16)  not null
        constraint ck_management_permission_type check (type in ('menu', 'action', 'data')),
    name        varchar(150) not null,
    parent_code varchar(150) references management_permission (code) on delete restrict,
    resource    varchar(150) not null,
    action      varchar(100) not null,
    sort_order  integer      not null default 0,
    active      boolean      not null default true
);

create table tenant_package
(
    id         bigint generated by default as identity primary key,
    code       varchar(100) not null unique,
    name       varchar(100) not null unique,
    status     varchar(16)  not null default 'active'
        constraint ck_tenant_package_status check (status in ('active', 'inactive')),
    is_default boolean      not null default false,
    max_users  integer      not null
        constraint ck_tenant_package_max_users check (max_users > 0),
    max_apps   integer      not null
        constraint ck_tenant_package_max_apps check (max_apps > 0),
    created_at timestamptz  not null default now(),
    updated_at timestamptz  not null default now(),
    constraint ck_tenant_package_positive_id check (id > 0)
);
create unique index uq_tenant_package_active_default
    on tenant_package (is_default) where is_default and status = 'active';

create table tenant_package_permission
(
    package_id      bigint       not null references tenant_package (id) on delete cascade,
    permission_code varchar(150) not null references management_permission (code) on delete restrict,
    created_at      timestamptz  not null default now(),
    primary key (package_id, permission_code)
);

create table tenant
(
    id         uuid primary key,
    name       varchar(200) not null,
    status     varchar(32)  not null default 'active' check (status in ('active', 'suspended', 'deleted')),
    created_at timestamptz  not null default now(),
    updated_at timestamptz  not null default now(),
    is_system  boolean      not null default false,
    package_id bigint references tenant_package (id) on delete restrict,
    constraint ck_tenant_system_package
        check ((is_system and package_id is null) or (not is_system and package_id is not null))
);

create table admin_account
(
    id               uuid primary key,
    username         varchar(100) not null unique,
    email            varchar(320) not null unique,
    status           varchar(32)  not null default 'active' check (status in ('active', 'disabled', 'locked')),
    last_tenant_id   uuid constraint fk_admin_last_tenant references tenant (id) on delete set null,
    security_version bigint       not null default 1,
    created_at       timestamptz  not null default now(),
    updated_at       timestamptz  not null default now(),
    phone            varchar(32),
    mfa_enabled      boolean      not null default false,
    mfa_type         varchar(32),
    last_login_at    timestamptz
);

create table tenant_membership
(
    id              uuid primary key,
    account_id      uuid        not null references admin_account (id) on delete cascade,
    tenant_id       uuid        not null references tenant (id) on delete cascade,
    membership_role varchar(32) not null default 'common'
        constraint ck_tenant_membership_role check (membership_role in ('super_admin', 'tenant_admin', 'common')),
    status          varchar(32) not null default 'active' check (status in ('active', 'suspended')),
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now(),
    unique (account_id, tenant_id)
);
create unique index uq_tenant_single_active_membership
    on tenant_membership (tenant_id) where status = 'active';
create index ix_membership_tenant on tenant_membership (tenant_id);

create table admin_role
(
    id          uuid primary key,
    tenant_id   uuid         not null references tenant (id) on delete cascade,
    name        varchar(100) not null,
    description text,
    system_role boolean      not null default false,
    created_at  timestamptz  not null default now(),
    updated_at  timestamptz  not null default now(),
    unique (tenant_id, name)
);

create table admin_role_permission
(
    role_id         uuid         not null references admin_role (id) on delete cascade,
    permission_code varchar(150) not null references management_permission (code) on delete restrict,
    created_at      timestamptz  not null default now(),
    primary key (role_id, permission_code)
);

create table membership_role_assignment
(
    membership_id uuid        not null references tenant_membership (id) on delete cascade,
    role_id       uuid        not null references admin_role (id) on delete cascade,
    created_at    timestamptz not null default now(),
    primary key (membership_id, role_id)
);

comment on column admin_account.last_tenant_id is 'UI preference only; never an authorization source';

create table admin_credential
(
    account_id          uuid primary key references admin_account (id) on delete cascade,
    password_hash       varchar(100) not null,
    password_changed_at timestamptz  not null default now(),
    created_at          timestamptz  not null default now(),
    updated_at          timestamptz  not null default now()
);

create table admin_refresh_session
(
    id               uuid primary key,
    account_id       uuid        not null references admin_account (id) on delete cascade,
    token_hash       char(64)    not null unique,
    security_version bigint      not null,
    expires_at       timestamptz not null,
    revoked_at       timestamptz,
    replaced_by      uuid,
    created_at       timestamptz not null default now(),
    last_used_at     timestamptz,
    user_agent       varchar(512),
    ip_address       varchar(64)
);
create index ix_admin_refresh_account on admin_refresh_session (account_id);
create index ix_admin_refresh_expiry on admin_refresh_session (expires_at) where revoked_at is null;

create table admin_mfa_secret
(
    account_id         uuid primary key references admin_account (id) on delete cascade,
    encrypted_secret   text        not null,
    backup_code_hashes jsonb       not null default '[]'::jsonb,
    updated_at         timestamptz not null default now()
);

create table admin_registration_code
(
    id         uuid primary key,
    email      varchar(320) not null,
    code_hash  char(64)     not null,
    expires_at timestamptz  not null,
    created_at timestamptz  not null default now(),
    unique (email, code_hash)
);
create index ix_admin_registration_expiry on admin_registration_code (expires_at);


create table pool_user
(
    id                uuid primary key,
    tenant_id         uuid         not null references tenant (id) on delete cascade,
    username          varchar(100) not null,
    email             varchar(320) not null,
    phone             varchar(32),
    password_hash     varchar(100),
    name              varchar(200) not null,
    avatar            text,
    status            varchar(32)  not null default 'active' check (status in ('active', 'disabled', 'locked')),
    email_verified    boolean      not null default false,
    phone_verified    boolean      not null default false,
    department        varchar(200),
    position          varchar(200),
    custom_attributes jsonb,
    last_login_at     timestamptz,
    created_at        timestamptz  not null default now(),
    updated_at        timestamptz  not null default now(),
    unique (tenant_id, username),
    unique (tenant_id, email),
    constraint ux_pool_user_tenant_id_id unique (tenant_id, id)
);
create index ix_pool_user_tenant on pool_user (tenant_id);
create table user_group
(
    id          uuid primary key,
    tenant_id   uuid         not null references tenant (id) on delete cascade,
    name        varchar(200) not null,
    description text,
    type        varchar(32)  not null default 'team',
    parent_id   uuid references user_group (id),
    created_at  timestamptz  not null default now(),
    updated_at  timestamptz  not null default now(),
    unique (tenant_id, name),
    constraint ux_user_group_tenant_id_id unique (tenant_id, id),
    constraint fk_user_group_parent_tenant
        foreign key (tenant_id, parent_id) references user_group (tenant_id, id)
);
create table position
(
    id            uuid primary key,
    tenant_id     uuid         not null references tenant (id) on delete cascade,
    name          varchar(200) not null,
    code          varchar(100) not null,
    description   text,
    department_id uuid,
    level         integer      not null default 1,
    sequence      varchar(100),
    max_count     integer,
    created_at    timestamptz  not null default now(),
    updated_at    timestamptz  not null default now(),
    unique (tenant_id, code),
    constraint fk_position_department_tenant
        foreign key (tenant_id, department_id) references user_group (tenant_id, id)
);
create table pool_role
(
    id          uuid primary key,
    tenant_id   uuid         not null references tenant (id) on delete cascade,
    name        varchar(100) not null,
    code        varchar(100) not null,
    description text,
    type        varchar(32)  not null default 'custom',
    permissions jsonb        not null default '{}'::jsonb,
    data_scope  varchar(32)  not null default 'self',
    parent_id   uuid references pool_role (id),
    created_at  timestamptz  not null default now(),
    updated_at  timestamptz  not null default now(),
    unique (tenant_id, code),
    constraint ux_pool_role_tenant_id_id unique (tenant_id, id),
    constraint fk_pool_role_parent_tenant
        foreign key (tenant_id, parent_id) references pool_role (tenant_id, id)
);
create table pool_permission
(
    id          uuid primary key,
    tenant_id   uuid         not null references tenant (id) on delete cascade,
    code        varchar(150) not null,
    name        varchar(150) not null,
    description text,
    type        varchar(32)  not null default 'operation',
    parent_id   uuid references pool_permission (id),
    resource    varchar(150) not null,
    action      varchar(100) not null,
    created_at  timestamptz  not null default now(),
    updated_at  timestamptz  not null default now(),
    unique (tenant_id, code),
    constraint ux_pool_permission_tenant_id_id unique (tenant_id, id),
    constraint fk_pool_permission_parent_tenant
        foreign key (tenant_id, parent_id) references pool_permission (tenant_id, id)
);
create table pool_user_group
(
    user_id   uuid not null references pool_user (id) on delete cascade,
    group_id  uuid not null references user_group (id) on delete cascade,
    tenant_id uuid not null,
    primary key (tenant_id, user_id, group_id),
    constraint fk_pool_user_group_user_tenant
        foreign key (tenant_id, user_id) references pool_user (tenant_id, id) on delete cascade,
    constraint fk_pool_user_group_group_tenant
        foreign key (tenant_id, group_id) references user_group (tenant_id, id) on delete cascade
);
create table pool_user_role
(
    user_id   uuid not null references pool_user (id) on delete cascade,
    role_id   uuid not null references pool_role (id) on delete cascade,
    tenant_id uuid not null,
    primary key (tenant_id, user_id, role_id),
    constraint fk_pool_user_role_user_tenant
        foreign key (tenant_id, user_id) references pool_user (tenant_id, id) on delete cascade,
    constraint fk_pool_user_role_role_tenant
        foreign key (tenant_id, role_id) references pool_role (tenant_id, id) on delete cascade
);
create table pool_group_admin
(
    group_id  uuid not null references user_group (id) on delete cascade,
    user_id   uuid not null references pool_user (id) on delete cascade,
    tenant_id uuid not null,
    primary key (tenant_id, group_id, user_id),
    constraint fk_pool_group_admin_user_tenant
        foreign key (tenant_id, user_id) references pool_user (tenant_id, id) on delete cascade,
    constraint fk_pool_group_admin_group_tenant
        foreign key (tenant_id, group_id) references user_group (tenant_id, id) on delete cascade
);
create table oauth_application
(
    id                        uuid primary key,
    tenant_id                 uuid         not null references tenant (id) on delete cascade,
    name                      varchar(200) not null,
    logo                      text,
    description               text,
    type                      varchar(32)  not null default 'web' check (type in ('web', 'native', 'spa', 'machine')),
    client_id                 varchar(100) not null unique,
    client_secret_hash        varchar(200),
    redirect_uris             jsonb        not null default '[]'::jsonb,
    post_logout_redirect_uris jsonb        not null default '[]'::jsonb,
    allowed_grant_types       jsonb        not null default '[
      "authorization_code"
    ]'::jsonb,
    scopes                    jsonb        not null default '[
      "openid",
      "profile",
      "email",
      "phone"
    ]'::jsonb,
    require_pkce              boolean      not null default true,
    require_consent           boolean      not null default true,
    access_token_lifetime     integer      not null default 900 check (access_token_lifetime between 60 and 86400),
    refresh_token_lifetime    integer      not null default 2592000 check (refresh_token_lifetime between 300 and 31536000),
    status                    varchar(32)  not null default 'active' check (status in ('active', 'disabled')),
    created_at                timestamptz  not null default now(),
    updated_at                timestamptz  not null default now(),
    unique (tenant_id, name),
    unique (tenant_id, id)
);
create index ix_oauth_application_tenant on oauth_application (tenant_id);

create table oauth2_authorization
(
    id                            varchar(100) primary key,
    tenant_id                     uuid         not null references tenant (id) on delete cascade,
    registered_client_id          varchar(100) not null,
    principal_name                varchar(200) not null,
    authorization_grant_type      varchar(100) not null,
    authorized_scopes             text,
    attributes                    text,
    state                         varchar(500),
    authorization_code_value      text,
    authorization_code_issued_at  timestamptz,
    authorization_code_expires_at timestamptz,
    authorization_code_metadata   text,
    access_token_value            text,
    access_token_issued_at        timestamptz,
    access_token_expires_at       timestamptz,
    access_token_metadata         text,
    access_token_type             varchar(100),
    access_token_scopes           text,
    refresh_token_value           text,
    refresh_token_issued_at       timestamptz,
    refresh_token_expires_at      timestamptz,
    refresh_token_metadata        text,
    oidc_id_token_value           text,
    oidc_id_token_issued_at       timestamptz,
    oidc_id_token_expires_at      timestamptz,
    oidc_id_token_metadata        text,
    oidc_id_token_claims          text,
    user_code_value               text,
    user_code_issued_at           timestamptz,
    user_code_expires_at          timestamptz,
    user_code_metadata            text,
    device_code_value             text,
    device_code_issued_at         timestamptz,
    device_code_expires_at        timestamptz,
    device_code_metadata          text
);
create index ix_oauth2_authorization_tenant_client on oauth2_authorization (tenant_id, registered_client_id);
create index ix_oauth2_authorization_state on oauth2_authorization (state);

create table oauth2_authorization_consent
(
    tenant_id            uuid         not null references tenant (id) on delete cascade,
    registered_client_id varchar(100) not null,
    principal_name       varchar(200) not null,
    authorities          text         not null,
    primary key (tenant_id, registered_client_id, principal_name)
);

create function resolve_oauth_tenant(client varchar) returns uuid
    language sql stable as $$
select tenant_id
from oauth_application
where id::text=client
$$;
create function set_oauth_authorization_tenant() returns trigger
    language plpgsql as $$
begin
    new.tenant_id
:=resolve_oauth_tenant(new.registered_client_id);
    if
new.tenant_id is null then raise exception 'unknown oauth registered client';
end if;
return new;
end $$;
create trigger trg_oauth2_authorization_tenant
    before insert or
update of registered_client_id
on oauth2_authorization
    for each row execute function set_oauth_authorization_tenant();
create trigger trg_oauth2_consent_tenant
    before insert or
update of registered_client_id
on oauth2_authorization_consent
    for each row execute function set_oauth_authorization_tenant();
create function cleanup_oauth_application_protocol() returns trigger
    language plpgsql as $$
begin
delete
from oauth2_authorization_consent
where registered_client_id = old.id::text;
delete
from oauth2_authorization
where registered_client_id = old.id::text;
return old;
end $$;
create trigger trg_oauth_application_protocol_cleanup
    before delete
    on oauth_application
    for each row execute function cleanup_oauth_application_protocol();

create table oauth2_signing_key
(
    id                    uuid primary key,
    tenant_id             uuid         not null references tenant (id) on delete cascade,
    key_id                varchar(100) not null,
    algorithm             varchar(32)  not null default 'RS256',
    public_jwk            jsonb        not null,
    encrypted_private_jwk text         not null,
    status                varchar(32)  not null default 'active' check (status in ('active', 'retired')),
    created_at            timestamptz  not null default now(),
    expires_at            timestamptz,
    unique (tenant_id, key_id)
);
create unique index uq_oauth2_active_signing_key on oauth2_signing_key (tenant_id) where status='active';


create table security_policy
(
    tenant_id                uuid primary key references tenant (id) on delete cascade,
    password_min_length      integer     not null default 8 check (password_min_length between 8 and 128),
    password_require_upper   boolean     not null default true,
    password_require_lower   boolean     not null default true,
    password_require_number  boolean     not null default true,
    password_require_special boolean     not null default true,
    password_max_age_days    integer     not null default 90 check (password_max_age_days between 0 and 3650),
    password_history_count   integer     not null default 5 check (password_history_count between 0 and 24),
    mfa_required             boolean     not null default false,
    login_attempt_limit      integer     not null default 5 check (login_attempt_limit between 1 and 100),
    lockout_duration_seconds integer     not null default 1800 check (lockout_duration_seconds between 60 and 86400),
    updated_at               timestamptz not null default now()
);

create table authentication_factor
(
    id               uuid primary key,
    subject_type     varchar(16) not null check (subject_type in ('admin', 'pool_user')),
    subject_id       uuid        not null,
    tenant_id        uuid references tenant (id) on delete cascade,
    factor_type      varchar(16) not null check (factor_type in ('totp', 'email')),
    encrypted_secret text,
    enabled          boolean     not null default false,
    last_totp_step   bigint,
    created_at       timestamptz not null default now(),
    updated_at       timestamptz not null default now(),
    check ((subject_type = 'admin' and tenant_id is null) or (subject_type = 'pool_user' and tenant_id is not null)),
    unique (subject_type, subject_id, factor_type)
);
create index ix_auth_factor_tenant on authentication_factor (tenant_id, subject_id);

create table authentication_recovery_code
(
    id         uuid primary key,
    factor_id  uuid        not null references authentication_factor (id) on delete cascade,
    code_hash  char(64)    not null,
    used_at    timestamptz,
    created_at timestamptz not null default now(),
    unique (factor_id, code_hash)
);

create table authentication_challenge
(
    id           uuid primary key,
    token_hash   char(64)    not null unique,
    subject_type varchar(16) not null check (subject_type in ('admin', 'pool_user', 'registration')),
    subject_id   uuid,
    tenant_id    uuid references tenant (id) on delete cascade,
    purpose      varchar(32) not null,
    factor_type  varchar(16) not null,
    code_hash    char(64),
    attempts     integer     not null default 0,
    max_attempts integer     not null default 5,
    expires_at   timestamptz not null,
    consumed_at  timestamptz,
    created_at   timestamptz not null default now(),
    last_sent_at timestamptz
);
create index ix_auth_challenge_subject on authentication_challenge (subject_type, subject_id, created_at desc);
create index ix_auth_challenge_expiry on authentication_challenge (expires_at) where consumed_at is null;

create table login_failure_state
(
    id              uuid primary key,
    subject_type    varchar(16)  not null,
    subject_key     varchar(400) not null,
    tenant_id       uuid,
    failed_attempts integer      not null default 0,
    locked_until    timestamptz,
    last_failed_at  timestamptz
);
create unique index uq_login_failure_subject on login_failure_state (subject_type, subject_key, coalesce(tenant_id,'00000000-0000-0000-0000-000000000000'::uuid));

create table password_history
(
    id            uuid primary key,
    subject_type  varchar(16)  not null,
    subject_id    uuid         not null,
    password_hash varchar(100) not null,
    created_at    timestamptz  not null default now()
);
create index ix_password_history_subject on password_history (subject_type, subject_id, created_at desc);

create table pool_user_device
(
    id                uuid primary key,
    tenant_id         uuid        not null references tenant (id) on delete cascade,
    user_id           uuid        not null references pool_user (id) on delete cascade,
    device_token_hash char(64)    not null,
    user_agent        varchar(512),
    ip_address        varchar(64),
    first_seen_at     timestamptz not null default now(),
    last_seen_at      timestamptz not null default now(),
    revoked_at        timestamptz,
    unique (tenant_id, user_id, device_token_hash)
);

create table federation_provider
(
    id                      uuid primary key,
    tenant_id               uuid          not null references tenant (id) on delete cascade,
    name                    varchar(120)  not null,
    issuer                  varchar(1000) not null,
    client_id               varchar(500)  not null,
    encrypted_client_secret text          not null,
    scopes                  jsonb         not null default '[
      "openid",
      "profile",
      "email"
    ]'::jsonb,
    claim_mapping           jsonb         not null default '{}'::jsonb,
    jit_provisioning        boolean       not null default false,
    status                  varchar(16)   not null default 'active' check (status in ('active', 'disabled')),
    created_at              timestamptz   not null default now(),
    updated_at              timestamptz   not null default now(),
    unique (tenant_id, name),
    unique (tenant_id, issuer, client_id)
);
create table external_identity_binding
(
    id            uuid primary key,
    tenant_id     uuid          not null references tenant (id) on delete cascade,
    provider_id   uuid          not null references federation_provider (id) on delete cascade,
    pool_user_id  uuid          not null references pool_user (id) on delete cascade,
    issuer        varchar(1000) not null,
    subject       varchar(1000) not null,
    claims        jsonb         not null default '{}'::jsonb,
    created_at    timestamptz   not null default now(),
    last_login_at timestamptz,
    unique (tenant_id, provider_id, issuer, subject),
    unique (tenant_id, provider_id, pool_user_id)
);
create table federation_login_transaction
(
    id                      uuid primary key,
    tenant_id               uuid        not null references tenant (id) on delete cascade,
    provider_id             uuid        not null references federation_provider (id) on delete cascade,
    state_hash              char(64)    not null unique,
    nonce_hash              char(64)    not null,
    encrypted_nonce         text        not null,
    encrypted_pkce_verifier text        not null,
    return_uri              text,
    expires_at              timestamptz not null,
    consumed_at             timestamptz,
    created_at              timestamptz not null default now()
);

create table brand_setting
(
    tenant_id       uuid primary key references tenant (id) on delete cascade,
    settings        jsonb       not null default '{}'::jsonb,
    company_name    varchar(200),
    logo            text,
    favicon         text,
    primary_color   varchar(16) not null default '#0369A1',
    secondary_color varchar(16),
    support_email   varchar(320),
    copyright_text  varchar(500),
    updated_at      timestamptz not null default now()
);
create table login_style
(
    tenant_id        uuid primary key references tenant (id) on delete cascade,
    logo             text,
    logo_dark        text,
    background_image text,
    background_color varchar(16)  not null default '#f5f7fa',
    primary_color    varchar(16)  not null default '#0369A1',
    title            varchar(200) not null default 'Easy1Auth',
    subtitle         varchar(500) not null default '企业级身份管理平台',
    custom_css       text,
    login_methods    jsonb        not null default '[
      "password"
    ]'::jsonb,
    social_providers jsonb        not null default '[]'::jsonb,
    created_at       timestamptz  not null default now(),
    updated_at       timestamptz  not null default now()
);
create table custom_domain
(
    id                  uuid primary key,
    tenant_id           uuid         not null references tenant (id) on delete cascade,
    domain              varchar(253) not null unique,
    status              varchar(16)  not null default 'pending' check (status in ('pending', 'verified', 'disabled')),
    verification_method varchar(16)  not null default 'dns' check (verification_method in ('dns', 'file')),
    verification_token  varchar(200) not null,
    verified_at         timestamptz,
    created_at          timestamptz  not null default now(),
    updated_at          timestamptz  not null default now()
);
create table message_template
(
    id         uuid primary key,
    tenant_id  uuid         not null references tenant (id) on delete cascade,
    type       varchar(16)  not null check (type in ('email', 'sms')),
    code       varchar(100) not null,
    name       varchar(200) not null,
    subject    varchar(500),
    content    text         not null,
    variables  jsonb        not null default '{}'::jsonb,
    is_default boolean      not null default false,
    status     varchar(16)  not null default 'active' check (status in ('active', 'inactive')),
    created_at timestamptz  not null default now(),
    updated_at timestamptz  not null default now(),
    unique (tenant_id, type, code)
);

create table audit_event
(
    id            uuid primary key,
    tenant_id     uuid references tenant (id) on delete cascade,
    actor_type    varchar(24)  not null,
    actor_id      uuid,
    actor_name    varchar(320),
    event_type    varchar(100) not null,
    action        varchar(100) not null,
    resource_type varchar(100) not null,
    resource_id   varchar(200),
    trace_id      varchar(100),
    method        varchar(16),
    ip_address    varchar(64),
    user_agent    varchar(512),
    outcome       varchar(16)  not null check (outcome in ('success', 'failure')),
    error_code    varchar(100),
    details       jsonb        not null default '{}'::jsonb,
    created_at    timestamptz  not null default now()
);
create index ix_audit_tenant_time on audit_event (tenant_id, created_at desc);
create index ix_audit_actor on audit_event (actor_type, actor_id, created_at desc);

create table webhook_subscription
(
    id               uuid primary key,
    tenant_id        uuid         not null references tenant (id) on delete cascade,
    name             varchar(200) not null,
    url              text         not null,
    events           jsonb        not null,
    secret_hash      char(64)     not null,
    encrypted_secret text         not null,
    status           varchar(16)  not null default 'active' check (status in ('active', 'disabled')),
    max_retries      integer      not null default 5 check (max_retries between 0 and 20),
    created_at       timestamptz  not null default now(),
    updated_at       timestamptz  not null default now(),
    unique (tenant_id, name)
);
create table delivery_outbox
(
    id              uuid primary key,
    tenant_id       uuid references tenant (id) on delete cascade,
    channel         varchar(16)  not null check (channel in ('email', 'webhook')),
    destination     text         not null,
    event_type      varchar(100) not null,
    payload         jsonb        not null,
    subscription_id uuid references webhook_subscription (id) on delete cascade,
    idempotency_key varchar(200) not null unique,
    status          varchar(16)  not null default 'pending' check (status in ('pending', 'processing', 'sent', 'dead')),
    attempts        integer      not null default 0,
    max_attempts    integer      not null default 5,
    available_at    timestamptz  not null default now(),
    lease_until     timestamptz,
    last_error      varchar(1000),
    created_at      timestamptz  not null default now(),
    sent_at         timestamptz
);
create index ix_delivery_claim on delivery_outbox (status, available_at) where status in ('pending','processing');
create table delivery_attempt
(
    id              uuid primary key,
    outbox_id       uuid        not null references delivery_outbox (id) on delete cascade,
    attempt_number  integer     not null,
    response_status integer,
    error_message   varchar(1000),
    attempted_at    timestamptz not null default now(),
    unique (outbox_id, attempt_number)
);

comment
on column login_style.custom_css is 'Compatibility storage only; never rendered on authentication pages';
comment
on table custom_domain is 'Phase 6 inventory only; ownership verification and TLS are external/deferred';


insert into management_permission (code, type, name, parent_code, resource, action, sort_order, active)
values ('menu:dashboard', 'menu', '控制台', null, 'dashboard', 'view', 10, true),
       ('menu:user-management', 'menu', '用户管理', null, 'user-management', 'view', 20, true),
       ('menu:user', 'menu', '用户列表', 'menu:user-management', 'user', 'view', 21, true),
       ('menu:group', 'menu', '用户组', 'menu:user-management', 'group', 'view', 22, true),
       ('menu:position', 'menu', '岗位管理', null, 'position', 'view', 23, true),
       ('menu:role', 'menu', '角色管理', null, 'role', 'view', 24, true),
       ('menu:permission', 'menu', '权限管理', null, 'permission', 'view', 25, true),
       ('menu:admin-user', 'menu', '管理员管理', null, 'admin-user', 'view', 26, true),
       ('menu:application', 'menu', '应用管理', null, 'application', 'view', 30, true),
       ('menu:social-identity-provider', 'menu', '社会化身份源', null, 'social-identity-provider', 'view', 31, true),
       ('menu:tenant', 'menu', '租户管理', null, 'tenant', 'view', 40, true),
       ('menu:brand-settings', 'menu', '品牌设置', null, 'brand-settings', 'view', 41, true),
       ('menu:security', 'menu', '安全设置', null, 'security', 'view', 42, true),
       ('menu:personalization', 'menu', '个性化设置', null, 'personalization', 'view', 43, true),
       ('menu:audit', 'menu', '审计日志', null, 'audit', 'view', 50, true),
       ('admin-user:list', 'action', '查看管理员列表', 'menu:admin-user', 'admin-user', 'list', 1, true),
       ('admin-user:stats', 'action', '查看管理员统计', 'menu:admin-user', 'admin-user', 'stats', 2, true),
       ('admin-user:read', 'action', '查看管理员详情', 'menu:admin-user', 'admin-user', 'read', 3, true),
       ('admin-user:update', 'action', '更新管理员', 'menu:admin-user', 'admin-user', 'update', 4, true),
       ('admin-user:status', 'action', '变更管理员状态', 'menu:admin-user', 'admin-user', 'status', 5, true),
       ('admin-user:reset-password', 'action', '重置管理员密码', 'menu:admin-user', 'admin-user', 'reset-password', 6,
        true),
       ('admin-user:reset-mfa', 'action', '重置管理员多因素认证', 'menu:admin-user', 'admin-user', 'reset-mfa', 7,
        true),
       ('admin-user:assign-role', 'action', '分配管理员角色', 'menu:admin-user', 'admin-user', 'assign-role', 8, true),
       ('admin-user:remove-tenant', 'action', '移除管理员租户关系', 'menu:admin-user', 'admin-user', 'remove-tenant', 9,
        true),
       ('tenant:list', 'action', '查看租户列表', 'menu:tenant', 'tenant', 'list', 1, true),
       ('tenant:create', 'action', '创建租户', 'menu:tenant', 'tenant', 'create', 2, true),
       ('tenant:read', 'action', '查看当前租户', 'menu:tenant', 'tenant', 'read', 3, true),
       ('tenant:owner-transfer', 'action', '转移租户管理员', 'menu:tenant', 'tenant', 'owner-transfer', 4, true),
       ('tenant:member-remove', 'action', '移除租户成员', 'menu:tenant', 'tenant', 'member-remove', 5, true),
       ('security:password-policy:read', 'action', '查看个人密码策略', 'menu:security', 'security',
        'password-policy-read', 1, true),
       ('security:password:change', 'action', '修改个人密码', 'menu:security', 'security', 'password-change', 2, true),
       ('security:mfa:read', 'action', '查看个人多因素认证状态', 'menu:security', 'security', 'mfa-read', 3, true),
       ('security:mfa:setup', 'action', '设置个人多因素认证', 'menu:security', 'security', 'mfa-setup', 4, true),
       ('security:mfa:enable', 'action', '启用个人多因素认证', 'menu:security', 'security', 'mfa-enable', 5, true),
       ('security:mfa:disable', 'action', '禁用个人多因素认证', 'menu:security', 'security', 'mfa-disable', 6, true),
       ('security:mfa:verify', 'action', '验证个人多因素认证', 'menu:security', 'security', 'mfa-verify', 7, true),
       ('security:mfa:email-code', 'action', '发送个人多因素认证邮件验证码', 'menu:security', 'security',
        'mfa-email-code', 8, true),
       ('application:list', 'action', '查看应用列表', 'menu:application', 'application', 'list', 1, true),
       ('application:stats', 'action', '查看应用统计', 'menu:application', 'application', 'stats', 2, true),
       ('application:read', 'action', '查看应用详情', 'menu:application', 'application', 'read', 3, true),
       ('application:create', 'action', '创建应用', 'menu:application', 'application', 'create', 4, true),
       ('application:update', 'action', '更新应用', 'menu:application', 'application', 'update', 5, true),
       ('application:delete', 'action', '删除应用', 'menu:application', 'application', 'delete', 6, true),
       ('application:status', 'action', '变更应用状态', 'menu:application', 'application', 'status', 7, true),
       ('application:regenerate-secret', 'action', '重置应用密钥', 'menu:application', 'application',
        'regenerate-secret', 8, true),
       ('social-identity-provider:list', 'action', '查看社会化身份源列表', 'menu:social-identity-provider',
        'social-identity-provider', 'list', 1, true),
       ('social-identity-provider:stats', 'action', '查看社会化身份源统计', 'menu:social-identity-provider',
        'social-identity-provider', 'stats', 2, true),
       ('social-identity-provider:read', 'action', '查看社会化身份源详情', 'menu:social-identity-provider',
        'social-identity-provider', 'read', 3, true),
       ('social-identity-provider:create', 'action', '创建社会化身份源', 'menu:social-identity-provider',
        'social-identity-provider', 'create', 4, true),
       ('social-identity-provider:update', 'action', '更新社会化身份源', 'menu:social-identity-provider',
        'social-identity-provider', 'update', 5, true),
       ('social-identity-provider:delete', 'action', '删除社会化身份源', 'menu:social-identity-provider',
        'social-identity-provider', 'delete', 6, true),
       ('audit:list', 'action', '查看审计日志列表', 'menu:audit', 'audit', 'list', 1, true),
       ('audit:stats', 'action', '查看审计日志统计', 'menu:audit', 'audit', 'stats', 2, true),
       ('audit:read', 'action', '查看审计日志详情', 'menu:audit', 'audit', 'read', 3, true),
       ('audit:cleanup', 'action', '清理审计日志', 'menu:audit', 'audit', 'cleanup', 4, true),
       ('admin-role:stats', 'action', '查看管理员角色统计', null, 'admin-role', 'stats', 1, true),
       ('admin-role:permissions-catalog', 'action', '查看管理员角色权限目录', null, 'admin-role', 'permissions-catalog',
        2, true),
       ('admin-role:list', 'action', '查看管理员角色列表', null, 'admin-role', 'list', 3, true),
       ('admin-role:read', 'action', '查看管理员角色详情', null, 'admin-role', 'read', 4, true),
       ('admin-role:create', 'action', '创建管理员角色', null, 'admin-role', 'create', 5, true),
       ('admin-role:update', 'action', '更新管理员角色', null, 'admin-role', 'update', 6, true),
       ('admin-role:delete', 'action', '删除管理员角色', null, 'admin-role', 'delete', 7, true),
       ('admin-role:assign', 'action', '分配管理员角色', null, 'admin-role', 'assign', 8, true),
       ('user:list', 'action', '查看用户列表', 'menu:user', 'user', 'list', 1, true),
       ('user:stats', 'action', '查看用户统计', 'menu:user', 'user', 'stats', 2, true),
       ('user:read', 'action', '查看用户详情', 'menu:user', 'user', 'read', 3, true),
       ('user:create', 'action', '创建用户', 'menu:user', 'user', 'create', 4, true),
       ('user:update', 'action', '更新用户', 'menu:user', 'user', 'update', 5, true),
       ('user:delete', 'action', '删除用户', 'menu:user', 'user', 'delete', 6, true),
       ('user:status', 'action', '变更用户状态', 'menu:user', 'user', 'status', 7, true),
       ('user:reset-password', 'action', '重置用户密码', 'menu:user', 'user', 'reset-password', 8, true),
       ('user:change-password', 'action', '修改用户密码', 'menu:user', 'user', 'change-password', 9, true),
       ('user:roles:read', 'action', '查看用户角色', 'menu:user', 'user', 'roles-read', 10, true),
       ('user:roles:assign', 'action', '分配用户角色', 'menu:user', 'user', 'roles-assign', 11, true),
       ('user:groups:read', 'action', '查看用户组', 'menu:user', 'user', 'groups-read', 12, true),
       ('user:groups:assign', 'action', '分配用户组', 'menu:user', 'user', 'groups-assign', 13, true),
       ('user:import:template', 'action', '下载用户导入模板', 'menu:user', 'user', 'import-template', 14, true),
       ('user:import', 'action', '导入用户', 'menu:user', 'user', 'import', 15, true),
       ('user-role:list', 'action', '查看用户角色列表', 'menu:role', 'user-role', 'list', 1, true),
       ('user-role:stats', 'action', '查看用户角色统计', 'menu:role', 'user-role', 'stats', 2, true),
       ('user-role:tree', 'action', '查看用户角色树', 'menu:role', 'user-role', 'tree', 3, true),
       ('user-role:read', 'action', '查看用户角色详情', 'menu:role', 'user-role', 'read', 4, true),
       ('user-role:create', 'action', '创建用户角色', 'menu:role', 'user-role', 'create', 5, true),
       ('user-role:update', 'action', '更新用户角色', 'menu:role', 'user-role', 'update', 6, true),
       ('user-role:delete', 'action', '删除用户角色', 'menu:role', 'user-role', 'delete', 7, true),
       ('user-role:users:read', 'action', '查看角色用户', 'menu:role', 'user-role', 'users-read', 8, true),
       ('user-role:users:assign', 'action', '分配角色用户', 'menu:role', 'user-role', 'users-assign', 9, true),
       ('user-role:users:remove', 'action', '移除角色用户', 'menu:role', 'user-role', 'users-remove', 10, true),
       ('user-role:user-roles:read', 'action', '查看用户角色关系', 'menu:role', 'user-role', 'user-roles-read', 11,
        true),
       ('user-role:user-roles:replace', 'action', '替换用户角色关系', 'menu:role', 'user-role', 'user-roles-replace',
        12, true),
       ('data-permission:list', 'action', '查看数据权限列表', 'menu:permission', 'data-permission', 'list', 1, true),
       ('data-permission:stats', 'action', '查看数据权限统计', 'menu:permission', 'data-permission', 'stats', 2, true),
       ('data-permission:tree', 'action', '查看数据权限树', 'menu:permission', 'data-permission', 'tree', 3, true),
       ('data-permission:read', 'action', '查看数据权限详情', 'menu:permission', 'data-permission', 'read', 4, true),
       ('data-permission:create', 'action', '创建数据权限', 'menu:permission', 'data-permission', 'create', 5, true),
       ('data-permission:update', 'action', '更新数据权限', 'menu:permission', 'data-permission', 'update', 6, true),
       ('data-permission:delete', 'action', '删除数据权限', 'menu:permission', 'data-permission', 'delete', 7, true),
       ('group:list', 'action', '查看用户组列表', 'menu:group', 'group', 'list', 1, true),
       ('group:tree', 'action', '查看用户组树', 'menu:group', 'group', 'tree', 2, true),
       ('group:stats', 'action', '查看用户组统计', 'menu:group', 'group', 'stats', 3, true),
       ('group:read', 'action', '查看用户组详情', 'menu:group', 'group', 'read', 4, true),
       ('group:create', 'action', '创建用户组', 'menu:group', 'group', 'create', 5, true),
       ('group:update', 'action', '更新用户组', 'menu:group', 'group', 'update', 6, true),
       ('group:delete', 'action', '删除用户组', 'menu:group', 'group', 'delete', 7, true),
       ('group:members:read', 'action', '查看用户组成员', 'menu:group', 'group', 'members-read', 8, true),
       ('group:members:add', 'action', '添加用户组成员', 'menu:group', 'group', 'members-add', 9, true),
       ('group:members:remove', 'action', '移除用户组成员', 'menu:group', 'group', 'members-remove', 10, true),
       ('group:admin:add', 'action', '添加用户组管理员', 'menu:group', 'group', 'admin-add', 11, true),
       ('group:admin:remove', 'action', '移除用户组管理员', 'menu:group', 'group', 'admin-remove', 12, true),
       ('position:list', 'action', '查看岗位列表', 'menu:position', 'position', 'list', 1, true),
       ('position:stats', 'action', '查看岗位统计', 'menu:position', 'position', 'stats', 2, true),
       ('position:read', 'action', '查看岗位详情', 'menu:position', 'position', 'read', 3, true),
       ('position:create', 'action', '创建岗位', 'menu:position', 'position', 'create', 4, true),
       ('position:update', 'action', '更新岗位', 'menu:position', 'position', 'update', 5, true),
       ('position:delete', 'action', '删除岗位', 'menu:position', 'position', 'delete', 6, true),
       ('webhook:list', 'action', '查看 Webhook 列表', null, 'webhook', 'list', 1, true),
       ('webhook:create', 'action', '创建 Webhook', null, 'webhook', 'create', 2, true),
       ('webhook:update', 'action', '更新 Webhook', null, 'webhook', 'update', 3, true),
       ('webhook:rotate-secret', 'action', '轮换 Webhook 密钥', null, 'webhook', 'rotate-secret', 4, true),
       ('webhook:delete', 'action', '删除 Webhook', null, 'webhook', 'delete', 5, true),
       ('security-policy:read', 'action', '查看租户安全策略', 'menu:security', 'security-policy', 'read', 9, true),
       ('security-policy:update', 'action', '更新租户安全策略', 'menu:security', 'security-policy', 'update', 10, true),
       ('brand:read', 'action', '查看品牌设置', 'menu:brand-settings', 'brand', 'read', 1, true),
       ('brand:update', 'action', '更新品牌设置', 'menu:brand-settings', 'brand', 'update', 2, true),
       ('login-style:read', 'action', '查看登录样式', 'menu:personalization', 'login-style', 'read', 1, true),
       ('login-style:update', 'action', '更新登录样式', 'menu:personalization', 'login-style', 'update', 2, true),
       ('custom-domain:list', 'action', '查看自定义域名列表', 'menu:personalization', 'custom-domain', 'list', 3, true),
       ('custom-domain:create', 'action', '创建自定义域名', 'menu:personalization', 'custom-domain', 'create', 4, true),
       ('custom-domain:verify', 'action', '验证自定义域名', 'menu:personalization', 'custom-domain', 'verify', 5, true),
       ('custom-domain:ssl', 'action', '更新自定义域名 SSL', 'menu:personalization', 'custom-domain', 'ssl', 6, true),
       ('custom-domain:delete', 'action', '删除自定义域名', 'menu:personalization', 'custom-domain', 'delete', 7, true),
       ('message-template:list', 'action', '查看消息模板列表', 'menu:personalization', 'message-template', 'list', 8,
        true),
       ('message-template:create', 'action', '创建消息模板', 'menu:personalization', 'message-template', 'create', 9,
        true),
       ('message-template:update', 'action', '更新消息模板', 'menu:personalization', 'message-template', 'update', 10,
        true),
       ('message-template:delete', 'action', '删除消息模板', 'menu:personalization', 'message-template', 'delete', 11,
        true),
       ('message-template:init', 'action', '初始化消息模板', 'menu:personalization', 'message-template', 'init', 12,
        true),
       ('data:platform:all', 'data', '平台全局数据', null, 'platform', 'all', 1, true),
       ('data:tenant:all', 'data', '当前租户全部数据', null, 'tenant', 'all', 2, true);

insert into tenant_package (code, name, status, is_default, max_users, max_apps)
values ('basic', '基础版', 'active', true, 100, 10);

insert into tenant_package_permission (package_id, permission_code)
select package.id, permission.code
from tenant_package package
         join management_permission permission on permission.code not in (
                                                                          'menu:admin-user', 'admin-user:list',
                                                                          'admin-user:stats', 'admin-user:read',
                                                                          'admin-user:update',
                                                                          'admin-user:status',
                                                                          'admin-user:reset-password',
                                                                          'admin-user:reset-mfa',
                                                                          'admin-user:assign-role',
                                                                          'admin-user:remove-tenant', 'menu:tenant',
                                                                          'tenant:list', 'tenant:create', 'tenant:read',
                                                                          'tenant:owner-transfer',
                                                                          'tenant:member-remove', 'data:platform:all'
    )
where package.code = 'basic';

create function reject_management_permission_change() returns trigger
    language plpgsql as $$
begin
    raise
exception using
        errcode = '55000',
        message = 'management permissions are immutable system catalog entries';
end;
$$;

create trigger trg_management_permission_immutable
    before update or
delete
on management_permission
    for each row execute function reject_management_permission_change();

create function enforce_single_active_default_tenant_package() returns trigger
    language plpgsql as $$
begin
    if
(
select count(*)
from tenant_package
where is_default
  and status = 'active') <> 1 then
        raise exception using
            errcode = '23514',
            message = 'tenant_package must contain exactly one active default package',
            constraint = 'ck_tenant_package_single_active_default';
end if;
return null;
end;
$$;

create
constraint trigger ck_tenant_package_single_active_default
    after insert or
update or
delete
on tenant_package
    deferrable initially deferred
    for each row execute function enforce_single_active_default_tenant_package();


insert into management_permission (code, type, name, parent_code, resource, action, sort_order, active)
values ('tenant-package:permissions-catalog', 'action', '查看租户套餐权限目录', 'menu:tenant', 'tenant-package',
        'permissions-catalog', 6, true),
       ('tenant-package:list', 'action', '查看租户套餐列表', 'menu:tenant', 'tenant-package', 'list', 7, true),
       ('tenant-package:read', 'action', '查看租户套餐详情', 'menu:tenant', 'tenant-package', 'read', 8, true),
       ('tenant-package:create', 'action', '创建租户套餐', 'menu:tenant', 'tenant-package', 'create', 9, true),
       ('tenant-package:update', 'action', '更新租户套餐', 'menu:tenant', 'tenant-package', 'update', 10, true),
       ('tenant-package:status', 'action', '变更租户套餐状态', 'menu:tenant', 'tenant-package', 'status', 11, true),
       ('tenant-package:permissions-replace', 'action', '替换租户套餐权限', 'menu:tenant', 'tenant-package',
        'permissions-replace', 12, true),
       ('tenant-package:delete', 'action', '删除租户套餐', 'menu:tenant', 'tenant-package', 'delete', 13, true);


insert into management_permission (code, type, name, parent_code, resource, action, sort_order, active)
values ('admin-user:create', 'action', '创建管理员账号', 'menu:admin-user', 'admin-user', 'create', 10, true);
