package com.easy1auth.admin.web;
import com.easy1auth.admin.security.TenantContextFilter; import com.easy1auth.directory.*; import com.easy1auth.foundation.web.ApiResponse; import com.easy1auth.tenant.TenantContext; import com.easy1auth.useraccess.UserAccessCatalogService; import jakarta.servlet.http.HttpServletRequest; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api/users") public class PoolUserController{
 private final PoolUserService users; private final DirectoryCatalogService directory; private final UserAccessCatalogService access; PoolUserController(PoolUserService users,DirectoryCatalogService directory,UserAccessCatalogService access){this.users=users;this.directory=directory;this.access=access;}
 @GetMapping public ApiResponse<?> list(HttpServletRequest r,@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="10")int pageSize,@RequestParam(required=false)String username,@RequestParam(required=false)String email,@RequestParam(required=false)String phone,@RequestParam(required=false)String name,@RequestParam(required=false)String status,@RequestParam(required=false)String department){return ApiResponse.ok(users.list(context(r).tenantId(),page,pageSize,username,email,phone,name,status,department));}
 @GetMapping("/stats") public ApiResponse<?> stats(HttpServletRequest r){return ApiResponse.ok(users.stats(context(r).tenantId()));}
 @GetMapping("/{id}") public ApiResponse<?> get(HttpServletRequest r,@PathVariable UUID id){return ApiResponse.ok(users.get(context(r).tenantId(),id));}
 @PostMapping public ApiResponse<?> create(HttpServletRequest r,@RequestBody PoolUserService.Input in){return ApiResponse.ok(users.create(context(r).tenantId(),in),"用户创建成功");}
 @PutMapping("/{id}") public ApiResponse<?> update(HttpServletRequest r,@PathVariable UUID id,@RequestBody PoolUserService.Input in){return ApiResponse.ok(users.update(context(r).tenantId(),id,in),"用户更新成功");}
 @DeleteMapping("/{id}") public ApiResponse<Void> delete(HttpServletRequest r,@PathVariable UUID id){users.delete(context(r).tenantId(),id);return ApiResponse.ok(null,"用户删除成功");}
 @PutMapping("/{id}/status") public ApiResponse<?> status(HttpServletRequest r,@PathVariable UUID id,@RequestBody StatusInput in){return ApiResponse.ok(users.status(context(r).tenantId(),id,in.status()),"状态更新成功");}
 @PostMapping("/{id}/reset-password") public ApiResponse<Void> password(HttpServletRequest r,@PathVariable UUID id,@RequestBody PasswordInput in){users.resetPassword(context(r).tenantId(),id,in.newPassword());return ApiResponse.ok(null,"密码重置成功");}
 @PostMapping("/{id}/change-password") public ApiResponse<Void> changePassword(HttpServletRequest r,@PathVariable UUID id,@RequestBody ChangePasswordInput in){users.changePassword(context(r).tenantId(),id,in.oldPassword(),in.newPassword());return ApiResponse.ok(null,"密码修改成功");}
 @GetMapping("/{id}/roles") public ApiResponse<?> roles(HttpServletRequest r,@PathVariable UUID id){return ApiResponse.ok(access.rolesForUser(context(r).tenantId(),id));}
 @PostMapping("/{id}/roles") public ApiResponse<Void> assignRoles(HttpServletRequest r,@PathVariable UUID id,@RequestBody RoleIds in){access.replaceUserRoles(context(r).tenantId(),id,in.roleIds());return ApiResponse.ok(null,"角色分配成功");}
 @GetMapping("/{id}/groups") public ApiResponse<?> groups(HttpServletRequest r,@PathVariable UUID id){return ApiResponse.ok(directory.groupsForUser(context(r).tenantId(),id));}
 @PostMapping("/{id}/groups") public ApiResponse<Void> assignGroups(HttpServletRequest r,@PathVariable UUID id,@RequestBody GroupIds in){directory.replaceUserGroups(context(r).tenantId(),id,in.groupIds());return ApiResponse.ok(null,"用户组分配成功");}
 private static TenantContext context(HttpServletRequest r){return (TenantContext)Objects.requireNonNull(r.getAttribute(TenantContextFilter.ATTRIBUTE));} public record StatusInput(String status){} public record PasswordInput(String newPassword){} public record ChangePasswordInput(String oldPassword,String newPassword){} public record RoleIds(List<UUID> roleIds){} public record GroupIds(List<UUID> groupIds){}
}
