package com.easy1auth.adminidentity;
import com.easy1auth.adminidentity.model.*; import com.easy1auth.foundation.id.UuidV7; import org.babyfish.jimmer.sql.JSqlClient; import org.babyfish.jimmer.sql.ast.Predicate; import org.babyfish.jimmer.sql.ast.mutation.SaveMode; import org.springframework.stereotype.Repository; import java.time.Instant; import java.util.*;
@Repository class AdminIdentityRepository{
 private static final AdminAccountEntityTable ACCOUNT=AdminAccountEntityTable.$; private static final AdminCredentialEntityTable CREDENTIAL=AdminCredentialEntityTable.$; private static final AdminRefreshSessionEntityTable SESSION=AdminRefreshSessionEntityTable.$;
 private final JSqlClient sql; private final RegistrationCodeNativeSql registrationCodes;
 AdminIdentityRepository(JSqlClient sql,RegistrationCodeNativeSql registrationCodes){this.sql=sql;this.registrationCodes=registrationCodes;}
 Optional<CredentialRow> findCredential(String login){var account=sql.createQuery(ACCOUNT).where(Predicate.or(ACCOUNT.username().lower().eq(login.toLowerCase()),ACCOUNT.email().lower().eq(login.toLowerCase()))).select(ACCOUNT).fetchOptional();if(account.isEmpty())return Optional.empty();var credential=sql.createQuery(CREDENTIAL).where(CREDENTIAL.accountId().eq(account.get().id())).select(CREDENTIAL.passwordHash()).fetchOptional();return credential.map(hash->new CredentialRow(toDomain(account.get()),hash));}
 Optional<AdminAccount> findActive(UUID id){return sql.createQuery(ACCOUNT).where(ACCOUNT.id().eq(id),ACCOUNT.status().eq("active")).select(ACCOUNT).fetchOptional().map(AdminIdentityRepository::toDomain);}
 boolean exists(String username,String email){return sql.createQuery(ACCOUNT).where(Predicate.or(ACCOUNT.username().lower().eq(username.toLowerCase()),ACCOUNT.email().lower().eq(email.toLowerCase()))).select(ACCOUNT.id()).exists();}
 AdminAccount create(String username,String email,String hash){UUID id=UuidV7.randomUuid();Instant now=Instant.now();var entity=AdminAccountEntityDraft.$.produce(d->d.setId(id).setUsername(username).setEmail(email).setPhone(null).setStatus("active").setLastTenantId(null).setSecurityVersion(1).setMfaEnabled(false).setMfaType(null).setLastLoginAt(null).setCreatedAt(now).setUpdatedAt(now));sql.saveCommand(entity).setMode(SaveMode.INSERT_ONLY).execute();sql.saveCommand(AdminCredentialEntityDraft.$.produce(d->d.setAccountId(id).setPasswordHash(hash).setPasswordChangedAt(now).setCreatedAt(now).setUpdatedAt(now))).setMode(SaveMode.INSERT_ONLY).execute();return toDomain(entity);}
 boolean consumeRegistrationCode(String email,String hash){return registrationCodes.consume(email,hash);}
 void issueRegistrationCode(UUID id,String email,String hash,Instant expires){registrationCodes.issue(id,email,hash,expires);}
 void recordLogin(UUID id){sql.createUpdate(ACCOUNT).set(ACCOUNT.lastLoginAt(),Instant.now()).set(ACCOUNT.updatedAt(),Instant.now()).where(ACCOUNT.id().eq(id)).execute();}
 void createSession(UUID id,UUID account,String hash,long version,Instant expires,String agent,String ip){Instant now=Instant.now();sql.saveCommand(AdminRefreshSessionEntityDraft.$.produce(d->d.setId(id).setAccountId(account).setTokenHash(hash).setSecurityVersion(version).setExpiresAt(expires).setRevokedAt(null).setReplacedBy(null).setCreatedAt(now).setLastUsedAt(null).setUserAgent(agent).setIpAddress(ip))).setMode(SaveMode.INSERT_ONLY).execute();}
 Optional<SessionRow> lockSession(String hash){var session=sql.createQuery(SESSION).where(SESSION.tokenHash().eq(hash),SESSION.revokedAt().isNull(),SESSION.expiresAt().gt(Instant.now())).select(SESSION).forUpdate().fetchOptional();if(session.isEmpty())return Optional.empty();return findAccount(session.get().accountId()).map(a->new SessionRow(session.get().id(),session.get().securityVersion(),a));}
 void rotate(UUID oldId,UUID replacement){sql.createUpdate(SESSION).set(SESSION.revokedAt(),Instant.now()).set(SESSION.lastUsedAt(),Instant.now()).set(SESSION.replacedBy(),replacement).where(SESSION.id().eq(oldId),SESSION.revokedAt().isNull()).execute();}
 void revoke(String hash){sql.createUpdate(SESSION).set(SESSION.revokedAt(),Instant.now()).where(SESSION.tokenHash().eq(hash),SESSION.revokedAt().isNull()).execute();}
 void revokeAll(UUID account){sql.createUpdate(SESSION).set(SESSION.revokedAt(),Instant.now()).where(SESSION.accountId().eq(account),SESSION.revokedAt().isNull()).execute();}
 void invalidateAccountSessions(UUID account){incrementVersion(account);revokeAll(account);}
 AdminAccount updateProfile(UUID id,String username,String email,String phone){var update=sql.createUpdate(ACCOUNT).set(ACCOUNT.updatedAt(),Instant.now()).where(ACCOUNT.id().eq(id));if(username!=null)update.set(ACCOUNT.username(),username);if(email!=null)update.set(ACCOUNT.email(),email);if(phone!=null)update.set(ACCOUNT.phone(),phone);if(update.execute()!=1)throw new IllegalStateException("account missing");return findActive(id).orElseThrow();}
 AdminAccount updateStatus(UUID id,String status){sql.createUpdate(ACCOUNT).set(ACCOUNT.status(),status).set(ACCOUNT.securityVersion(),ACCOUNT.securityVersion().plus(1L)).set(ACCOUNT.updatedAt(),Instant.now()).where(ACCOUNT.id().eq(id)).execute();return findAccount(id).orElseThrow();}
 void resetPassword(UUID id,String hash){sql.createUpdate(CREDENTIAL).set(CREDENTIAL.passwordHash(),hash).set(CREDENTIAL.passwordChangedAt(),Instant.now()).set(CREDENTIAL.updatedAt(),Instant.now()).where(CREDENTIAL.accountId().eq(id)).execute();incrementVersion(id);}
 AdminAccount resetMfa(UUID id){sql.createUpdate(ACCOUNT).set(ACCOUNT.mfaEnabled(),false).set(ACCOUNT.mfaType(),(String)null).set(ACCOUNT.securityVersion(),ACCOUNT.securityVersion().plus(1L)).set(ACCOUNT.updatedAt(),Instant.now()).where(ACCOUNT.id().eq(id)).execute();return findAccount(id).orElseThrow();}
 AdminAccount enableMfa(UUID id,String type){sql.createUpdate(ACCOUNT).set(ACCOUNT.mfaEnabled(),true).set(ACCOUNT.mfaType(),type).set(ACCOUNT.securityVersion(),ACCOUNT.securityVersion().plus(1L)).set(ACCOUNT.updatedAt(),Instant.now()).where(ACCOUNT.id().eq(id)).execute();return findAccount(id).orElseThrow();}
 private void incrementVersion(UUID id){sql.createUpdate(ACCOUNT).set(ACCOUNT.securityVersion(),ACCOUNT.securityVersion().plus(1L)).set(ACCOUNT.updatedAt(),Instant.now()).where(ACCOUNT.id().eq(id)).execute();}
 private Optional<AdminAccount> findAccount(UUID id){return sql.createQuery(ACCOUNT).where(ACCOUNT.id().eq(id)).select(ACCOUNT).fetchOptional().map(AdminIdentityRepository::toDomain);}
 private static AdminAccount toDomain(AdminAccountEntity a){return new AdminAccount(a.id(),a.username(),a.email(),a.phone(),a.status(),a.securityVersion(),a.lastTenantId(),a.mfaEnabled(),a.mfaType(),a.lastLoginAt(),a.createdAt(),a.updatedAt());}
 record CredentialRow(AdminAccount account,String passwordHash){} record SessionRow(UUID id,long sessionSecurityVersion,AdminAccount account){}
}
